### PR TITLE
README - Make instructions SnowEx specific.

### PR DESCRIPTION
**Pull request by jomey**

### CODE REVIEW

**Comment by jomey** [comment]
The checks are currently failing since the training repository only allows changes to the `contributors` folder. I will figure out later how to get this in once you guys give your thumbs up.

**Comment by lsetiawan** [comment]
@jomey You'll have to add yourself to the `ADMIN_USERS` otherwise, it won't allow you to add/modify this repo: https://github.com/snowex-hackweek/learning-git/blob/main/.ci_scripts/check-files.py#L12

**Comment by lsetiawan** [comment]
Also, if you have admin access to this Repo, you need to install `probot-auto-merge`

Screenshot from 2021-06-14 09-45-21

**Comment by jomey** [comment]
Have you checked out the ['auto-merge' feature](https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository) for this?
Looks like it could do the trick as well

**Comment by lsetiawan** [comment]
> Have you checked out the 'auto-merge' feature for this?

Oooh nice! Go for it! 😄 I didn't know that existed. Haha

**Comment by lsetiawan** [comment]
Oh wait, reading that further seems like you'd have to enable auto-merge for each individual PR's. Not all PR's

> If you allow auto-merge for pull requests in your repository, people with write permissions can configure individual pull requests in the repository to merge automatically when all merge requirements are met.

**Comment by jomey** [comment]
> Oh wait, reading that further seems like you'd have to enable auto-merge for each individual PR's. Not all PR's
> 
> > If you allow auto-merge for pull requests in your repository, people with write permissions can configure individual pull requests in the repository to merge automatically when all merge requirements are met.

Ah .. good catch. Maybe something that still can be automated when adding the 'auto-merge' badge? Or is that something from the probot integration?

**Comment by lsetiawan** [comment]
> is that something from the probot integration

The probot looks for that label in the PR to auto-merge. It appears that the built in Github requires a person intervention. FYI, those settings can be found here: https://github.com/snowex-hackweek/learning-git/blob/main/.github/auto-merge.yml

**Review by lsetiawan — APPROVED** [review]
I think this README is great! Do you mind contributing similar thing for the upstream repo that you forked from? :) Thanks! I think this is ready to merge. I just added you as the admin. It's still failing because it's still using the old file not the updated one, so please ignore. Thanks!

**Pull request merged**
